In [1]:
import torch
print(torch.__version__)

2.9.1+cpu


In [2]:
vector = [1.0, 0.5, 3.7, -0.5]
matrix = [[1,2],[3,4]]


In [3]:
vector_tensor = torch.tensor(vector)
matrix_tensor = torch.tensor(matrix)


In [6]:
print(
    f"Вектор:\n{vector_tensor} \nМатрица: \n{matrix_tensor}",
    f"Размер вектора {vector_tensor.shape},{matrix_tensor.shape}",
    f"Суммарное количество элементов {vector_tensor.numel()}, {matrix_tensor.numel()}",
    f"Количество размерностей {vector_tensor.dim()},{matrix_tensor.dim()}",
    f"Какого типа элементы вектора {vector_tensor.dtype}, {matrix_tensor.dtype}",
    sep =  "\n\n",
)

Вектор:
tensor([ 1.0000,  0.5000,  3.7000, -0.5000]) 
Матрица: 
tensor([[1, 2],
        [3, 4]])

Размер вектора torch.Size([4]),torch.Size([2, 2])

Суммарное количество элементов 4, 4

Количество размерностей 1,2

Какого типа элементы вектора torch.float32, torch.int64


In [7]:
vector_tensor[2]

tensor(3.7000)

In [8]:
vector_tensor[:3]

tensor([1.0000, 0.5000, 3.7000])

In [9]:
matrix[0][1]

2

In [10]:
matrix_tensor[0,1]

tensor(2)

In [12]:
matrix_tensor[:,1]

tensor([2, 4])

In [14]:
matrix_tensor[[0,0,1,1],[0,1,0,1]]

tensor([1, 2, 3, 4])

In [15]:
matrix_tensor[[1,1,0,0,1],:]

tensor([[3, 4],
        [3, 4],
        [1, 2],
        [1, 2],
        [3, 4]])

In [17]:
bool_mask = torch.tensor([False,True,True,False])
print(
    vector_tensor[bool_mask],
    sep = "\n\n",
)

tensor([0.5000, 3.7000])


In [19]:
bool_mask_1 = torch.tensor([[True,False],[False,True]])
bool_mask_2 = torch.tensor([False,True])
print(
    matrix_tensor[bool_mask_1],
    matrix_tensor[bool_mask_2,:],
    matrix_tensor[:,bool_mask_2],
    sep = "\n\n",
)

tensor([1, 4])

tensor([[3, 4]])

tensor([[2],
        [4]])


In [20]:
torch.tensor(
    [0.,1.,-2.,3.],
    dtype=torch.int,
)

tensor([ 0,  1, -2,  3], dtype=torch.int32)

In [21]:
torch.ones(2,3,dtype = torch.double)


tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [22]:
torch.linspace(0,10,5,dtype = torch.float64)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000], dtype=torch.float64)

In [23]:
torch.randint(
    -5,
    5,
    (2,3),
)

tensor([[ 1,  4, -5],
        [ 2, -2, -4]])

In [24]:
torch.rand(1,3,dtype = torch.float32)


tensor([[0.6344, 0.0054, 0.0892]])

In [25]:
torch.randn(2,3,dtype = torch.float16)


tensor([[ 0.9351, -0.7427, -0.4866],
        [ 1.4512, -0.4353, -1.0127]], dtype=torch.float16)

In [26]:
# Для многих конструкторов есть версия с ..._like, позволяющая создать тензор
#  той же размерности, что и другой тензор, вместо прямого указания размерностей.
# dtype также наследуется, если явно не указать обратного.
print(
    f"zeros_like:\n{torch.zeros_like(matrix_tensor)}",
    f"ones_like:\n{torch.ones_like(vector_tensor, dtype=torch.bool)}",
    f"rand_like:\n{torch.rand_like(vector_tensor)}",
    f"randn_like:\n{torch.randn_like(matrix_tensor, dtype=torch.float)}",
    f"randint_like:\n{torch.randint_like(matrix_tensor, 0, 3)}",
    sep="\n\n",
)

zeros_like:
tensor([[0, 0],
        [0, 0]])

ones_like:
tensor([True, True, True, True])

rand_like:
tensor([0.5146, 0.5562, 0.3188, 0.2225])

randn_like:
tensor([[-0.1145, -0.0142],
        [ 1.2194, -0.6119]])

randint_like:
tensor([[1, 1],
        [1, 0]])


In [27]:
# Константа взаимодействует с любым тензором поэлементно.
print(
    f"Изначальный вектор:\n{vector_tensor}",
    f"Умножение или деление вектора на константу:\n{vector_tensor * 2}",
    f"Прибавление или вычитание константы из вектора:\n{vector_tensor + 4}",
    f"Логические операции также поддерживаются:\n{vector_tensor > 0}",
    f"Возведение в степень как поэлементная операция:\n{vector_tensor ** 2}",
    f"В том числе можно и в обратную сторону:\n{2 ** vector_tensor}",
    sep="\n\n",
)

Изначальный вектор:
tensor([ 1.0000,  0.5000,  3.7000, -0.5000])

Умножение или деление вектора на константу:
tensor([ 2.0000,  1.0000,  7.4000, -1.0000])

Прибавление или вычитание константы из вектора:
tensor([5.0000, 4.5000, 7.7000, 3.5000])

Логические операции также поддерживаются:
tensor([ True,  True,  True, False])

Возведение в степень как поэлементная операция:
tensor([ 1.0000,  0.2500, 13.6900,  0.2500])

В том числе можно и в обратную сторону:
tensor([ 2.0000,  1.4142, 12.9960,  0.7071])


In [28]:
vector_tensor_2 = torch.tensor([0.,1.,-0.5,-2.])
print(
    f"Изначальные вектора:\n{vector_tensor}\n{vector_tensor_2}",
    f"Сумма/разница векторов (поэлементно):\n{vector_tensor + vector_tensor_2}",
    f"Умножение/деление векторов (поэлементно):\n{vector_tensor * vector_tensor_2}",
    sep="\n\n",
)

Изначальные вектора:
tensor([ 1.0000,  0.5000,  3.7000, -0.5000])
tensor([ 0.0000,  1.0000, -0.5000, -2.0000])

Сумма/разница векторов (поэлементно):
tensor([ 1.0000,  1.5000,  3.2000, -2.5000])

Умножение/деление векторов (поэлементно):
tensor([ 0.0000,  0.5000, -1.8500,  1.0000])


In [29]:
matrix_tensor_1 = torch.tensor([[1,-1],[-2,4]],dtype = torch.float)
matrix_tensor_2 = torch.tensor([[3,1],[2,1]],dtype = torch.float)
print(
    f"Изначальные матрицы:\n{matrix_tensor_1}\n{matrix_tensor_2}",
    f"Поэлементная сумма матриц\n{matrix_tensor_1 + matrix_tensor_2}",
    f"Обычный символ произведения даст поэлементное произведение матриц\n{matrix_tensor_1 * matrix_tensor_2}",
    (
        f"Матричное произведение двух матриц:"
        f"\n\nПервая на вторую\n{matrix_tensor_1 @ matrix_tensor_2}"
        f"\n\nВторая на первую\n{torch.mm(matrix_tensor_2, matrix_tensor_1)}"
    ),
    sep="\n\n\n",
)

Изначальные матрицы:
tensor([[ 1., -1.],
        [-2.,  4.]])
tensor([[3., 1.],
        [2., 1.]])


Поэлементная сумма матриц
tensor([[4., 0.],
        [0., 5.]])


Обычный символ произведения даст поэлементное произведение матриц
tensor([[ 3., -1.],
        [-4.,  4.]])


Матричное произведение двух матриц:

Первая на вторую
tensor([[1., 0.],
        [2., 2.]])

Вторая на первую
tensor([[1., 1.],
        [0., 2.]])


In [30]:
# Много удобных функций для подсчёта статистик
#  и поэлементных математических операций.
print(
    f"Изначальный вектор:\n{vector_tensor}",
    f"Сумма элементов:\n{vector_tensor.sum()}",
    f"Максимальное значение:\n{vector_tensor.max()}",
    f"Минимальное значение:\n{vector_tensor.min()}",
    f"Среднее арифметическое элементов:\n{vector_tensor.mean()}",
    f"Значения по модулю:\n{vector_tensor.abs()}",
    f"Округлить значения до ближайшего целого:\n{vector_tensor.round()}",
    f"Поэлементный квадратичный корень:\n{vector_tensor.sqrt()}",
    f"Поэлементный косинус:\n{vector_tensor.cos()}",
    "И многое-многое другое... Есть очень хорошая документация — https://pytorch.org/docs/stable/torch.html.",
    sep="\n\n",
)

Изначальный вектор:
tensor([ 1.0000,  0.5000,  3.7000, -0.5000])

Сумма элементов:
4.699999809265137

Максимальное значение:
3.700000047683716

Минимальное значение:
-0.5

Среднее арифметическое элементов:
1.1749999523162842

Значения по модулю:
tensor([1.0000, 0.5000, 3.7000, 0.5000])

Округлить значения до ближайшего целого:
tensor([1., 0., 4., -0.])

Поэлементный квадратичный корень:
tensor([1.0000, 0.7071, 1.9235,    nan])

Поэлементный косинус:
tensor([ 0.5403,  0.8776, -0.8481,  0.8776])

И многое-многое другое... Есть очень хорошая документация — https://pytorch.org/docs/stable/torch.html.


In [31]:
print(
    f"Изначальные вектора:\n{vector_tensor}\n{vector_tensor_2}",
    f"Объединять вдоль существующей оси:\n{torch.cat([vector_tensor, vector_tensor_2], dim=0)}",
    f"Объединять вдоль новой оси:\n{torch.stack([vector_tensor, vector_tensor_2], dim=0)}",
    f"Изменять размерность:\n{vector_tensor.reshape(2, 2)}",
    sep="\n\n",
)

Изначальные вектора:
tensor([ 1.0000,  0.5000,  3.7000, -0.5000])
tensor([ 0.0000,  1.0000, -0.5000, -2.0000])

Объединять вдоль существующей оси:
tensor([ 1.0000,  0.5000,  3.7000, -0.5000,  0.0000,  1.0000, -0.5000, -2.0000])

Объединять вдоль новой оси:
tensor([[ 1.0000,  0.5000,  3.7000, -0.5000],
        [ 0.0000,  1.0000, -0.5000, -2.0000]])

Изменять размерность:
tensor([[ 1.0000,  0.5000],
        [ 3.7000, -0.5000]])


In [32]:
# Почти для всех поэлементных операций есть 2 версии:
#  1. Cтандартная - к примеру, vector_tensor.sqrt()
#      поэлементно берёт корень квадратный и ВОЗВРАЩАЕТ НОВЫЙ тензор, но НЕ МЕНЯЕТ ОРИГИНАЛЬНЫЙ тензор.
#  2. In-place - к примеру, vector_tensor.sqrt_()
#      поэлементно берёт корень квадратный и ВОЗВРАЩАЕТ ОРИГИНАЛЬНЫЙ тензор, и МЕНЯЕТ ОРИГИНАЛЬНЫЙ тензор.
vector_tensor = torch.tensor([1, -2, 3, -4])

print(
    f"Смотрим на оригинальный вектор:\n{vector_tensor}",
    f"Применяем стандартную поэлементную функцию модуля числа:\n{vector_tensor.abs()}",
    f"Смотрим на оригинальный вектор второй раз:\n{vector_tensor}",
    f"Применяем in-place поэлементную функцию модуля числа:\n{vector_tensor.abs_()}",
    f"Смотрим на оригинальный вектор третий раз:\n{vector_tensor}",
    sep="\n\n",
)

Смотрим на оригинальный вектор:
tensor([ 1, -2,  3, -4])

Применяем стандартную поэлементную функцию модуля числа:
tensor([1, 2, 3, 4])

Смотрим на оригинальный вектор второй раз:
tensor([ 1, -2,  3, -4])

Применяем in-place поэлементную функцию модуля числа:
tensor([1, 2, 3, 4])

Смотрим на оригинальный вектор третий раз:
tensor([1, 2, 3, 4])


Задание 1. Импортируйте PyTorch и посмотрите версию.

In [46]:
import torch
print(torch.__version__)

2.9.1+cpu


Задание 2. Создать одномерный тензор чисел от 0 до 9.


In [45]:
tensor_ob = torch.tensor([i for i in range(0,10)],dtype = torch.int64)
print(
    f"Наш созданный тензор: \n{tensor_ob}"
)

Наш созданный тензор: 
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Задание 3. 
Для тензора, созданного в задании 2, выведите

тип элементов
размер
количество размерностей

In [51]:
print(
    f"Тип элементов: \n{tensor_ob.dtype}",
    f"Размер тензора: \n{tensor_ob.shape}",
    f"Количество размерностей: \n{tensor_ob.dim()}",
    sep = "\n\n"
)

Тип элементов: 
torch.int64

Размер тензора: 
torch.Size([10])

Количество размерностей: 
1


Задание 4.  Разделите тензор из задания 2 на две половины (левую - начало тензора и правую - его конец). Выведите обе эти половины.

In [53]:
print(
    f"Первая половина тензора: \n{tensor_ob[:6]}",
    f"Вторая половина тензора: \n{tensor_ob[5:]}",
    sep = "\n\n"
)

Первая половина тензора: 
tensor([0, 1, 2, 3, 4, 5])

Вторая половина тензора: 
tensor([5, 6, 7, 8, 9])


Задание 5. Создайте вещественный массив размером  3×4 , в котором все элементы равны 1.

In [55]:
tensor_ob_1 = torch.ones((3,4),dtype = torch.float)
print(
    f"Созданный массив: \n{tensor_ob_1}",
    sep = "\n\n"
)

Созданный массив: 
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Задание 6. Создайте логический массив размером  5×2 , в котором все элементы равны True.

In [56]:
tensor_ob_bool = torch.ones((5,2),dtype = torch.bool)
print(
    f"Логический массив: \n{tensor_ob_bool}",
    sep = "\n\n"
)

Логический массив: 
tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True]])


Задание 7. Создайте одномерный тензор с последовательностью вещественных чисел от 1 до 15 включительно, в котором каждый следующий элемент отличается от предыдущего на 0.5

In [59]:
tensor_ob_step = torch.arange(1,16,0.5, dtype = torch.float)
print(
    f" Полученный тензор: \n{tensor_ob_step}",
    sep = "\n\n"
)

 Полученный тензор: 
tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000, 11.0000, 11.5000, 12.0000, 12.5000,
        13.0000, 13.5000, 14.0000, 14.5000, 15.0000, 15.5000])


Задание 8. Создайте одномерный тензор, в котором ровно 20 значений. Первой значение 1, последнее значение 10, а расстояние между каждыми двумя соседними элементами одинаково.

In [64]:
tensor_twenty = torch.linspace(1,10,20)
print(
    f"Получили: \n{tensor_twenty}",
    sep = "\n\n"
)

Получили: 
tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])


Задание 9. Создайте двумерный тензор случайных вещественных значений размером  4×3  из равномерного распределения на полуинтервале [0, 1).

In [65]:
tensor_pavn  = torch.rand((4,3),dtype = torch.float32)
print(
    f"Получили: \n{tensor_pavn}",
    sep = "\n\n"
)

Получили: 
tensor([[0.4216, 0.2437, 0.2719],
        [0.4769, 0.3253, 0.8273],
        [0.9445, 0.5912, 0.7177],
        [0.8844, 0.1909, 0.9606]])


Задание 10. Создайте одномерный тензор 100 случайных "школьных оценок", а именно целых значений из промежутка от 3 до 5 включительно.

In [123]:
tensor_school = torch.randint(3,6,(100,))
print(
    f"Получилось: \n{tensor_school}",
    sep = '\n\n'
)

Получилось: 
tensor([3, 4, 4, 3, 4, 3, 3, 4, 3, 3, 3, 5, 5, 5, 4, 3, 5, 5, 5, 4, 3, 5, 5, 5,
        3, 4, 5, 4, 3, 4, 5, 5, 3, 4, 4, 4, 5, 5, 4, 4, 4, 3, 3, 4, 3, 5, 4, 4,
        5, 5, 4, 3, 5, 5, 3, 5, 4, 5, 4, 3, 4, 4, 4, 4, 4, 3, 3, 4, 5, 5, 5, 3,
        4, 4, 3, 4, 3, 5, 4, 4, 4, 3, 5, 5, 3, 3, 3, 5, 4, 5, 3, 4, 5, 4, 4, 4,
        3, 5, 4, 5])


In [124]:
tensor_school.dim()

1

Задание 11. Для тензора "школьных отенок", созданного в задании 10, посчитайте и выведите минимум, максимум и среднее арифметическое.

In [125]:
print(
    f"Минимальное число: \n{torch.min(tensor_school)}",
    f"Максимальное число: \n{torch.max(tensor_school)}",
    f"Среднее значение: \n{torch.sum(tensor_school/len(tensor_school))}",
    sep = "\n\n"
)

Минимальное число: 
3

Максимальное число: 
5

Среднее значение: 
4.029999732971191


Задание 12. Создайте булеву маску для массива "школьных оценок" из задания 10, в которой True будет стоять для первых 5 оценок и для последних 5 оценок, а остальные значения будут False.

In [131]:
bool_mask = torch.tensor(tensor_school, dtype = torch.bool)
print(bool_mask) 


tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True])


C:\Users\User\AppData\Local\Temp\ipykernel_35572\2658149126.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  bool_mask = torch.tensor(tensor_school, dtype = torch.bool)


In [133]:
bool_mask[5:95] = False
print(bool_mask) 

tensor([ True,  True,  True,  True,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True,  True,  True,  True,  True])


Задание 13. Отфильтруйте тензор "школьных оценок", созданный в задании 10, с помощью маски, созданной в задании 12, оставив тем самым только первые и последние пять оценок.

In [134]:
print(
    f"Фильтрация: \n{tensor_school[bool_mask]}",
    sep = "\n\n"
)

Фильтрация: 
tensor([3, 4, 4, 3, 4, 4, 3, 5, 4, 5])


Задание 14. Создайте маску для тензора "школьных оценок", в которой для каждой "пятерки" будет стоять True, а для остальных значений будет стоять False.

In [138]:
booling_mask = torch.tensor(tensor_school)
for i in range(0,100):
    if booling_mask[i] == 5:
        booling_mask[i] = 1
    else:
        booling_mask[i] = 0
booling_mask_1 = torch.tensor(booling_mask,dtype=torch.bool)
print(booling_mask_1)

tensor([False, False, False, False, False, False, False, False, False, False,
        False,  True,  True,  True, False, False,  True,  True,  True, False,
        False,  True,  True,  True, False, False,  True, False, False, False,
         True,  True, False, False, False, False,  True,  True, False, False,
        False, False, False, False, False,  True, False, False,  True,  True,
        False, False,  True,  True, False,  True, False,  True, False, False,
        False, False, False, False, False, False, False, False,  True,  True,
         True, False, False, False, False, False, False,  True, False, False,
        False, False,  True,  True, False, False, False,  True, False,  True,
        False, False,  True, False, False, False, False,  True, False,  True])


C:\Users\User\AppData\Local\Temp\ipykernel_35572\2088555401.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  booling_mask = torch.tensor(tensor_school)
C:\Users\User\AppData\Local\Temp\ipykernel_35572\2088555401.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  booling_mask_1 = torch.tensor(booling_mask,dtype=torch.bool)


Задание 15. Извлеките все "пятерки" из тензора "школьных отенок", созданного в задании 10, и занесите их в новый тензор.

In [142]:
new_tensor = []
for i in range(0,100):
    if tensor_school[i] == 5:
        new_tensor.append(5)
print(new_tensor)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


Задание 16. Преобразуйте тензор "школьных оценок" в двумерный тензор с 5 строками размером  5×20

In [147]:
print(tensor_school.reshape(5,20))

tensor([[3, 4, 4, 3, 4, 3, 3, 4, 3, 3, 3, 5, 5, 5, 4, 3, 5, 5, 5, 4],
        [3, 5, 5, 5, 3, 4, 5, 4, 3, 4, 5, 5, 3, 4, 4, 4, 5, 5, 4, 4],
        [4, 3, 3, 4, 3, 5, 4, 4, 5, 5, 4, 3, 5, 5, 3, 5, 4, 5, 4, 3],
        [4, 4, 4, 4, 4, 3, 3, 4, 5, 5, 5, 3, 4, 4, 3, 4, 3, 5, 4, 4],
        [4, 3, 5, 5, 3, 3, 3, 5, 4, 5, 3, 4, 5, 4, 4, 4, 3, 5, 4, 5]])



Задание 17. Выполните стыковку тензоров a и b по вертикали. Желаемый результат: новый тензор размером  4×5 .
a = torch.arange(2, 10, 2).reshape(2, -1)
b = torch.repeat(1, 10).reshape(2, -1)
print(a)
print(b)

In [165]:
a = torch.arange(2, 22, 2).reshape(2, -1)

b = torch.tensor([1]).repeat(10).reshape(2, -1)
print(a)
print(b)


tensor([[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]])
tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])


In [190]:
a_b = torch.vstack((a,b))
print(a_b)
print(a_b.dim())

tensor([[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
2


Задание 18. Выполните стыковку тензоров a и b по горизонтали.

Вход:

a = torch.arange(2, 10, 2).reshape(2, -1)

b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером  2×10 .

In [188]:
a = torch.arange(2,22,2).reshape(2,-1)
b = torch.arange(1,11,1).reshape(2,-1)
tensor_ab = torch.cat((a,b),dim = 1)
print(a)
print(b)
print(f"Стыковка тензоров: \n{tensor_ab}",sep = "\n\n")
print(tensor_ab.dim())


tensor([[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]])
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
Стыковка тензоров: 
tensor([[ 2,  4,  6,  8, 10,  1,  2,  3,  4,  5],
        [12, 14, 16, 18, 20,  6,  7,  8,  9, 10]])
2


Задание 19. Получите все элементы от 5 до 10 в тензоре a.

Вход:

a = torch.tensor([2, 6, 1, 9, 10, 3, 27])

Желаемый результат:

tensor([6, 9, 10])

In [181]:
a = torch.tensor([2,6,1,9,10,3,27])
b = torch.tensor([i for i in a if i >= 5 and i <= 10])
print(b)
        

tensor([ 6,  9, 10])


Задание 20. Вывести первую строку матрицы из задания 18.

In [189]:
print(
    f"Вывод первой строки тензора из задания 18: \n{tensor_ab[0][:]}",
    sep = "\n\n"
)

Вывод первой строки тензора из задания 18: 
tensor([ 2,  4,  6,  8, 10,  1,  2,  3,  4,  5])


Задание 21. Вывести последний столбец матрицы из задания 17.

In [191]:
print(
    f"Вывод первого столбца из задания 17: \n{a_b[:,0]}",
    sep = "\n\n"
)

Вывод первого столбца из задания 17: 
tensor([ 2, 12,  1,  6])


Задание 22. Вывести центральную часть матрицы из задания 17 (размерностью  2×3 ).

In [203]:
print(
    f"Вывод центральной матрице: \n{a_b[[1,2],1:4]}",
    sep = "\n\n"
)

Вывод центральной матрице: 
tensor([[14, 16, 18],
        [ 2,  3,  4]])


Задание 23. Вставить в двумерный терзор из задания 17 строку из минимального элемента перед первой строкой.

In [225]:
new_tensor_a_b = torch.cat([torch.tensor([torch.min(a_b)]).repeat(5).reshape(1,-1),a_b],dim = 0)
print(
    f"Вставим строку из минимального элемента из тензора 17: \n{new_tensor_a_b}",
    sep = "\n\n"
)

Вставим строку из минимального элемента из тензора 17: 
tensor([[ 1,  1,  1,  1,  1],
        [ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


Задание 24. В тензоре, полученном при выполнении задания 23, каждый элемент заменить его корнем квадратным.

In [226]:
print(
    f"Квадратный корень: \n{new_tensor_a_b.sqrt()}",
    sep = "\n\n"
)

Квадратный корень: 
tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.4142, 2.0000, 2.4495, 2.8284, 3.1623],
        [3.4641, 3.7417, 4.0000, 4.2426, 4.4721],
        [1.0000, 1.4142, 1.7321, 2.0000, 2.2361],
        [2.4495, 2.6458, 2.8284, 3.0000, 3.1623]])


Задание 25. Заменить в тензоре из задания 18 все значения, кратные 3 или 2 на число 1, а остальные – оставить без изменений.

In [229]:
for j in range(0,2):
    for i in range(0,len(tensor_ab[0])):
        if tensor_ab[j][i] % 2 == 0 or tensor_ab[j][i] % 3 == 0:
            tensor_ab[j][i] = 1
            
    
print(
    f"Полученный тензор: \n{tensor_ab}",
    sep = "\n\n"
)
    

Полученный тензор: 
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 7, 1, 1, 1]])
